<?php
/**
 * Admin Settings Page Service.
 *
 * @package {{NS}}\Admin
 */

namespace {{NS}}\Admin;

use {{NS}}\Contracts\Registrable;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Settings_Page.
 */
class Settings_Page implements Registrable {

	/**
	 * Register admin menu and settings hooks.
	 *
	 * @return void
	 */
	public function register(): void {
		add_action( 'admin_menu', array( $this, 'add_menu_page' ) );
		add_action( 'admin_init', array( $this, 'register_settings' ) );
	}

	/**
	 * Add admin menu page.
	 *
	 * @return void
	 */
	public function add_menu_page() {
		// TODO: SECURITY - Verify capability before rendering page link.
		add_options_page(
			__( '{{PLUGIN_NAME}} Settings', '{{SLUG}}' ),
			__( '{{PLUGIN_NAME}}', '{{SLUG}}' ),
			'manage_options',
			'{{SLUG}}',
			array( $this, 'render_page' )
		);
	}

	/**
	 * Register settings using Settings API.
	 *
	 * @return void
	 */
	public function register_settings() {
		// TODO: SECURITY - Sanitize input callbacks during register_setting.
		register_setting( '{{PREFIX}}_options_group', '{{PREFIX}}_option_name' );
	}

	/**
	 * Render admin page content.
	 *
	 * @return void
	 */
	public function render_page() {
		// TODO: SECURITY - Check user capability before proceeding.
		?>
		<div class="wrap">
			<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>
			<form method="post" action="options.php">
				<?php
				// TODO: SECURITY - Verify nonce automatically generated by settings_fields.
				settings_fields( '{{PREFIX}}_options_group' );
				do_settings_sections( '{{SLUG}}' );
				submit_button();
				?>
			</form>
		</div>
		<?php
	}
}
