name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    name: Code Sniffer (PHPCS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS
        run: composer lint

  phpunit:
    name: PHPUnit Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.2', '8.3']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: composer test
{{CI_NODE_JOB}}
